noun = input("Enter noun : ")
tobe = input("Choose to be verb : ")
pastparticiple = input("Past Participle : ")
obj = input("Enter object : ")
wh_question1 = input("Enter the first wh_question : ")
wh_question2 = input("Enter the second wh_question : ")
### Paragraph need complete
print("He met her at a ",noun,".")
print("She",tobe,"so outstanding, many guys were chasing after her, while he was so normal, nobody paid attention to him.")
print("At the end of the party, he",pastparticiple,"her to have coffee with him.")
print("She was so surprised, but due to being polite,",obj," promised.")
print("They sat in a nice coffee shop, he was too nervous to say anything, she felt uncomfortable, and she thought, “Please, let me go home.”")
print("Suddenly he asked the waiter:")
print("“Would you please give me some salt? I’d like to put it in my coffee.”")
print("Everybody stared at him, so strange!")
print("His face turned red, but still, he put the salt in his coffee and drank it.")
print("She asked him curiously:")
print(wh_question1,"do you have this hobby?")
print("He replied:")
print(wh_question2,"I was a little boy I lived near the sea, I liked playing in the sea; I could feel the taste of the sea, just like the taste of this salty coffee.")
print("Now every time I have salty coffee, I always think of my childhood, think of my hometown, I miss my hometown so much, I miss my parents who are still living there.”")
