obj1 = input("Enter the first object :")
obj2 = input("Enter the second object :")
obj3 = input("Enter the third object :")
obj4 = input("Enter the fourth object :")
adverb = input("Choose adverb : ")
complex_word = input("Choose complex word : ")

print("One day in the 1920’s, a ",obj1," asked if he could visit a woman at her home.")
print(" When he arrived at her home,",obj2," was wearing a hat on her head. ")
print(obj3," today may not understand what this story means. ")
print("But any ",obj4," in the 1920’s would understand. ")
print("The hat said that the girl would like to go out with him. ")
print(adverb,", men liked sitting in the girl’s house to talk, to meet her mother, to have something to eat and to listen to her play the piano. ")
print(complex_word," women would like to go on a date, to go out somewhere interesting. ")
print("This new style of dating began to take the place of the old system of visiting in society in the early 20th century. ")
print("Nowadays, it is very popular around the world.")